name: Test, Build, Release from MASTER

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    name: Flutter Test (Ubuntu-Latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - uses: subosito/flutter-action@v1
      - run: flutter test
  
  build_web:
    name: Build Web App (Ubuntu-Latest)
    needs: test
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - uses: subosito/flutter-action@v1
      - run: flutter build web
      
  build_apk:
    name: Build APK (Ubuntu-Latest)
    needs: test
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - uses: subosito/flutter-action@v1
      - run: flutter build apk --split-per-abi
      
  build_linux:
    name: Build Linux (Ubuntu-Latest)
    needs: test
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - uses: subosito/flutter-action@v1
      - run: flutter config --enable-linux-desktop
      - run: flutter create --platforms linux .
      - run: flutter build linux 
  
  build_windows:
    name: Build Windows (Windows Latest)
    needs: test
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - uses: subosito/flutter-action@v1
      - run: flutter config --enable-windows-desktop
      - run: flutter doctor
      - run: flutter build windows
