name: Test, Build, Release from MASTER

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # test:
    # name: Flutter Test (Ubuntu Latest)
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
    #   - name: Setup Java
    #     uses: actions/setup-java@v1
    #     with:
    #       java-version: '14.x'
    #   - name: Setup flutter
    #     uses: subosito/flutter-action@v1
    #   - name: Run flutter tests
    #     run: flutter test
      
  build_linux:
    name: Build Linux (Ubuntu Latest)
    # needs: test
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v1
      - name: Enable platforms and desktops
        run: |
          flutter create --platforms linux .
          flutter create --platforms web .
          flutter create --platforms android .
          flutter config --enable-linux-desktop
      - name: Build Web
        run: flutter build web
      - name: Build APK
        run: flutter build apk --split-per-abi
      - name: Build Linux
        run: flutter build linux
  
  # build_windows:
  #   name: Build Windows (Windows Latest)
  #   needs: test
  #   continue-on-error: true
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: '14.x'
  #     - name: Setup flutter
  #       uses: subosito/flutter-action@v1
  #     - name: Enable platform and desktop
  #       run: |
  #         flutter create --platforms windows .
  #         flutter config --enable-windows-desktop
  #     - name: Build Windows
  #       run: flutter build windows
